apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook-database.fullname" . }}-headless
  labels:
    {{- include "guestbook-database.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "guestbook-database.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
