apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-runner.fullname" . }}-token
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.github.accessToken | quote }}
