apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: guestbook-database
  namespace: {{ .Release.Namespace }}
  labels:
    app: guestbook-database
spec:
  namespaceSelector:
    matchNames:
      - guestbook
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook-database
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
