apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guestbook-backend.fullname" . }}
  labels:
    {{- include "guestbook-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "guestbook-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "guestbook-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: guestbook-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: GET_HOSTS_FROM
              value: "env"
            - name: REDIS_LEADER_SERVICE_HOST
              value: {{ .Values.database.host | quote }}
            - name: REDIS_FOLLOWER_SERVICE_HOST
              value: {{ .Values.database.host | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
