{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "log-collector.fullname" . }}
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
{{- end }}
